<!-- DO NOT EDIT THIS FILE-->
<!-- IF YOU EDIT THIS FILE, YOU WILL BE KICKED OUT OF THE INTERNSHIP-->

<html>
   <?php include 'partials/header.php';?>
   <body class=" pi">
      <?php include 'partials/navbar.php';?>
      <section class="main-section">
         <div class="container">
            <div class="row">
               <div class="col-md-12 col-sm-6 col-xs-12">
                  <div class="col-md-6 col-xs-12">
                     <div class="intern-block border-blue">
                        <img src="https://res.cloudinary.com/sirmatrix/image/upload/v1554481074/IMG_20181023_113952.jpg" alt="Sanusi Mubaraq">
                        <h6>Sanusi Mubaraq</h6>
                        <p>Data Scientist</p>
                        <ul class="list">
                           <li><a href="https://twitter.com/WeirdMatrix" target="_blank"<i class="fab fa-twitter fa-2x"></i></a></li>
                           <li><a href="https://twitter.com/WeirdMatrix" target="_blank"<i class="fab fa-github fa-2x"></i></a></li>
                           <li><a href="https://medium.com/@Mubaraqsanusi" target="_blank"<i class="fab fa-medium fa-2x"></i></a></li>
                        </ul>
                     </div>
                  </div>
                  <div class="col-md-6 col-xs-12 align-items-center">
                     <div class="intern-bio border-blue">
                        <h6>About Me</h6>
                        <p>I am a software engineer with a year of experience. I'm interested in automation and computer vision, but my major focus is on designing web and machine learning solutions.</p>
                        <br />
                        <h6>Skills</h6>
                        <p> Python | PHP | JavaScript</p>
                     </div>
                  </div>
               </div>
            </div>
         </div>
         </div>
      </section>
   </body>
   <?php include 'partials/footer.php';?>
</html>
